apiVersion: rbac.authorization.k8s.io/v1
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: aklearn
  name: order-service-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
# Source: hello/templates/rbac
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: order-service-role-binding
  namespace: aklearn
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: order-service-role
  apiGroup: ""